language: node_js

os: linux

node_js:
  - 9

script:
  - npm run lint
  - npm run test
  - npm run build

notifications:
  email:
    on_failure: change

cache:
  yarn: true
  directories:
    - node_modules
