language: node_js

os: linux

node_js:
  - 10

script:
  - yarn run lint
  - yarn run test
  - yarn run build

notifications:
  email:
    on_failure: change

cache:
  yarn: true
  directories:
    - node_modules
